name: Terraform Deploy

on:
  push:
    branches: ["main"]
    paths:
      - "day5-infra/terraform/**"
      - "day5-infra/governance/**"

jobs:
  deploy-dev:
    runs-on: ubuntu-latest
    environment: dev
    defaults:
      run:
        working-directory: day5-infra/terraform/envs/dev
    steps:
      - uses: actions/checkout@v4

      - uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.7.5

      - name: Init
        run: terraform init

      - name: Apply (dev)
        run: terraform apply -auto-approve

  deploy-prod:
    runs-on: ubuntu-latest
    needs: deploy-dev
    environment: prod
    defaults:
      run:
        working-directory: day5-infra/terraform/envs/prod
    steps:
      - uses: actions/checkout@v4

      - uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.7.5

      - name: Init
        run: terraform init

      - name: Apply (prod)
        run: terraform apply -auto-approve
